### ISSUE TITLE
Support for new `elm.json` file in 0.19

### ISSUE THREAD

**Issue by r-k-b** [gyzerok/elm-outdated#10]
Running `elm-outdated` on a codebase updated to 0.19 fails with the error:
```
There is no elm-package.json in the directory your are running elm-outdated from.
```

**Comment by gyzerok** [comment]
Hello @r-k-b!

Thank you for your report. There is an ongoing work on 0.19 support. I hope it will be released soon.

**Comment by gyzerok** [comment]
@r-k-b support has just been released, feel free to `npm i -g elm-outdated@latest`
