### ISSUE TITLE
elm-outdated no longer works for elm 0.19 projects

### ISSUE THREAD

**Issue by mthiems** [gyzerok/elm-outdated#12]
Changes in the package.elm-lang.org API have resulted in returning the wrong data (and in the wrong format) for 0.19 projects. As a result, when using elm-outdated for 0.19 projects, it always just says:
`Your elm.json is corrupted`

The problem and fix wasn't trivial to find, but turns out to be a very simple fix. PR incoming shortly.

**Comment by gyzerok** [comment]
Was fixed by PR from @mthiems
